version: '3.8'

services:
  arrit_mysql:
    container_name: arrit_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: arrit_mysql
      MYSQL_USER: u-user
      MYSQL_PASSWORD: p-password
    volumes:
      - arrit_mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  arrit_redis:
    container_name: arrit_redis
    image: redis:6.2.6-alpine
    restart: on-failure
    environment:
      REDIS_PASSWORD:
    volumes:
      - arrit_redis:/data
    ports:
      - '6379:6379'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  arrit_phpmyadmin:
    container_name: arrit_phpmyadmin
    image: phpmyadmin
    restart: 'unless-stopped'
    environment:
      VIRTUAL_HOST: phpmyadmin.arrit.localhost
      UPLOAD_LIMIT: 100M
      PMA_ARBITRARY: 1
      PMA_HOST: arrit_mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '8080:80'
    depends_on:
      - arrit_mysql
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  arrit_rabbitmq:
    container_name: arrit_rabbitmq
    image: 'rabbitmq:3.9.13-management'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    hostname: arrit_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  arrit_mysql:
  arrit_redis:
